from .admin import AdminInterface
from .admin_login_session import AdminLoginSessionInterface
from .channel import ChannelInterface
from .device import DeviceInterface
from .proxy import ProxyInterface
from .subscriber import SubscriberInterface
from .task import TaskInterface
from .task_argument import TaskArgumentInterface
from .task_make import TaskMakeInterface
from .tg_app import TgAppInterface
from .tg_client import TgClientInterface
from .u_name import UNameInterface
from .bios import BioInterface
from .avatars import AvatarInterface
from .nicknames import NicknameInterface
from .channel_reactions import ChannelReactionsInterface
from .tasks_for_make import TaskForMakeInterface
